---
title: "Beyond Fiction and Nonfiction: Machine Learning for Book Genre Classification"
format: html
author: "Natalie Truesdell"
date: "2026-01-16"
categories: [books, classifiers, analysis]
---

## Beyond Fiction and Nonfiction: Machine Learning for Book Genre Classification

As a reader, one of the most frustrating experiences is going to your local library to discover a new book and finding everything grouped by fiction/nonfiction and sorted by the dreaded author last name. The literary landscape is expanding with new sub- and hybrid-genres which spoils readers with options but also complicates how books are classified into genres. The traditional method of manually sorting genre by hand is time-inefficient, subjective to the sorter’s tastes, and takes a growing number of resources and manpower.

### Is machine learning the solution?

Machine learning offers a potential way to simplify this process by automatically classifying books based on their content but comes with its own set of problems. 

Genres are constantly overlapping, and it can be difficult to identify the dividing line between them (Dermawan & Latifah, 2025). How does the model decide which genre to put a book that seems to be 50% historical literature and 50% romance? In addition, the model is only as good as the data it is trained on, but most of the available datasets have a heavy class imbalance with a lot of entries of one genre and not a lot for another (Dermawan & Latifah, 2025). What data is available is a determining factor, as having a data set that includes the genre label as well as the full text of the book would give you more information than a single-sentence description. Dudar raises the point that books are "internally heterogeneous," meaning the content of the book differs depending on which chapter you are on, or even where in the chapter you are (Dudar 2026).

These are factors to keep in mind when trying to find the optimal model that balances accuracy and computational efficiency.

### How is text processed?

The starting point for text processing is usually removing stop words like "and," "a," "the," which are words that don't give you information on the topic of the book but instead make your data more noisy. After that, data scientists tend to "shop around" by trying different processing techniques and seeing which works best.

In their paper, "Optimizing Book Genre Classification through AI on a Web Platform", Dermawan & Latifa used a combination of advanced text processing and Natural Language Processing (NLP) techniques to analyze book descriptions and synopses.

Their next step, and one of the most popular processing techniques, was to use Term Frequency-Inverse Document Frequency (TF-IDF). You break down each synopsis into individual words and calculate how frequently a word appears in a given document (an individual synopsis) versus how frequently it appears in the corpus (the collection of documents)(Dermawan & Latifa, 2025). If words like “dystopian” or “humanity” tend to have a higher TF-IDF for documents classified as science fiction, this teaches the model how to identify that genre.

They also used word embeddings, a popular NLP technique that preserves contextual relationships between words (Dermawan & Latifa, 2025). By using this, your model can differentiate between words with multiple meanings in different contexts like “toast and jam” versus “traffic jam”.

### What model works best?

After comparing several approaches, as shown in @tbl-models, Dermawan and Latifah's best performing model was a Support Vector Machines (SVM) compared to models like Gradient Boosting Machine, Random Forest, and K-Nearest-Neighbors. 

After optimizing the model’s parameters, it achieved a final test accuracy of 0.79, which means that it correctly classified the genre of 79% of the books in the test set and a F1 score of 0.78, which balances the model’s ability to correctly identify positives versus the proportion of actual positives it successfully detected (Dermawan & Latifah, 2025).

SVMs are a common choice for analyzing text data because of their ability to handle a large number of unique words and complex decision boundaries. However, SVMs tend to take a long time to implement and train, and aren't as interpretable as other methods (Dudar, 2026).

::: {#tbl-models}
Table 1: Model Performance Comparison

| Metric   | SVM  | Gradient Boosting Machine | Random Forest | KNN  |
|----------|------|---------------------------|---------------|------|
| Accuracy | 0.73 | 0.69                      | 0.67          | 0.65 |
| F1 Score | 0.70 | 0.68                      | 0.63          | 0.64 |
:::

The overall performance of this model is pretty good, but its generalizability, ability to be reused on other problems with different data, is limited. If you look at the data in @tbl-genre, you can see that the data they worked with has a large class imbalance and consisted mostly of Thriller novels. The dataset also only covers six main generes and no subgenres, which is concerning.

::: {#tbl-genre}
Table 2: Number of Titles for Each Genre

| Genre     | Data Type |
|-----------|-----------|
| Thriller  | 1623      |
| Learning  | 1347      |
| Fantasy   | 876       |
| Crime     | 500       |
| Adventure | 200       |
| Romance   | 111       |
| **Total** | 4567      |
:::

### Is there another way?
With the current literary landscape, limiting a book to a single genre classification might not be the best choice. Dudar discusses how after struggling with the performance of his logistic regression model, Calvo Tello landed on multi-label classification (Dudar, 2026). This means that a single book could be labeled as multiple genres or sub-genres. 

This method is interesting because it uses the automation of machine learning but then adds back in the human factor. It can be up to the discretion of the book publisher or individual librarian where they want the book to go. In this way, machine learning is one of the tools in their toolkit, but not the absolute authority.


### What more can we do?

While there is still further research to be done into how to further optimize this model, these findings indicate that machine learning could be a useful tool for libraries and publishers. By reducing the time and effort required for manual sorting, institutions could redirect resources toward expanding collections, improving accessibility, or supporting emerging authors (Dermawan & Latifah, 2025). Special attention has to be paid to the data used to train the models, but this provides a good launching off point for future exploration into the usefulness of machine learning in genre classification.

## References

Dermawan, Fariz, and Noor Latifah. “Optimizing Book Genre Classification through AI on a Web Platform.” Bit-Tech, vol. 8, no. 1, 10 Aug. 2025, pp. 1200–1211, https://doi.org/10.32877/bt.v8i1.3001. Accessed 24 Oct. 2025.
Dudar, Julia. “Data Analysis for Genre.” Survey of Methods in Computational Literary Studies, CLS INFRA, methods.clsinfra.io/analysis-genre.html. Accessed 16 Jan. 2026.
